### PR TITLE
change query in userRepo line 18

### PR DESCRIPTION
**Pull request by nooshinpourhassan**

### CODE REVIEW

**Comment by nooshinpourhassan** [comment]
change query in user repository and CreateTable.sql line 16

**Review by farzadafi — APPROVED** [review]
💯

**Review by farzadafi — APPROVED** [review]
💯

**Review by farzadafi — APPROVED** [review]
💯

**Review by farzadafi — APPROVED** [review]
thanks, Miss PourHassan for fixing some bug

**Pull request merged**
